spring:
  application:
    name: chat_bot

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_bot_db
    username: admin
    password: defender
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
